"use client";

import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { AnimatedOrbs } from "@/components/ui/AnimatedOrbs";
import { useLang } from "@/contexts/LangContext";

function TermsEN() {
  return (
    <>
      <h1 className="text-3xl font-bold text-tx mb-8">Terms of Service</h1>
      <p className="text-tx2 text-sm mb-6">Last updated: March 2026</p>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">1. Acceptance of Terms</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          By accessing and using Genfy (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">2. Service Description</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          Genfy is an AI-powered platform that generates professional videos from product images. The service uses multiple AI engines to create video content based on user-provided images and prompts.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">3. User Accounts</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">4. Token System & Payments</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          Video generation consumes tokens based on the AI engine used. Tokens are non-transferable and tied to your account. Refunds are processed automatically when generation fails due to system errors. Subscription payments are processed through AbacatePay.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">5. Acceptable Use</h2>
        <p className="text-tx2 text-sm leading-relaxed mb-3">You agree not to:</p>
        <ul className="list-disc pl-6 text-tx2 text-sm leading-relaxed space-y-2">
          <li>Upload images that contain illegal, harmful, or offensive content</li>
          <li>Use the service to generate misleading or deceptive content</li>
          <li>Attempt to reverse-engineer or abuse the AI models</li>
          <li>Exceed rate limits or circumvent usage restrictions</li>
          <li>Resell or redistribute generated content without proper rights</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">6. Intellectual Property</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          You retain ownership of images you upload. Videos generated by the service may be used for your commercial purposes. The Genfy platform, brand, and underlying technology remain our intellectual property.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">7. Limitation of Liability</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          Genfy is provided &quot;as is&quot; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability shall not exceed the amount paid by you in the previous 12 months.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">8. Changes to Terms</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the modified terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">9. Contact</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          For questions about these Terms, contact us through our social media channels or at the app support section.
        </p>
      </section>
    </>
  );
}

function TermsPT() {
  return (
    <>
      <h1 className="text-3xl font-bold text-tx mb-8">Termos de Servi&ccedil;o</h1>
      <p className="text-tx2 text-sm mb-6">&Uacute;ltima atualiza&ccedil;&atilde;o: Mar&ccedil;o de 2026</p>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">1. Aceita&ccedil;&atilde;o dos Termos</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          Ao acessar e usar o Genfy (&quot;o Servi&ccedil;o&quot;), voc&ecirc; concorda em estar vinculado a estes Termos de Servi&ccedil;o. Se n&atilde;o concordar, por favor n&atilde;o use nossos servi&ccedil;os.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">2. Descri&ccedil;&atilde;o do Servi&ccedil;o</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          O Genfy &eacute; uma plataforma alimentada por IA que gera v&iacute;deos profissionais a partir de imagens de produtos. O servi&ccedil;o usa m&uacute;ltiplos motores de IA para criar conte&uacute;do de v&iacute;deo baseado em imagens e prompts fornecidos pelo usu&aacute;rio.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">3. Contas de Usu&aacute;rio</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          Voc&ecirc; &eacute; respons&aacute;vel por manter a confidencialidade das credenciais da sua conta e por todas as atividades que ocorrem sob sua conta. Voc&ecirc; deve nos notificar imediatamente sobre qualquer uso n&atilde;o autorizado.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">4. Sistema de Tokens e Pagamentos</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          A gera&ccedil;&atilde;o de v&iacute;deos consome tokens baseados no motor de IA utilizado. Tokens s&atilde;o intransfer&iacute;veis e vinculados &agrave; sua conta. Reembolsos s&atilde;o processados automaticamente quando a gera&ccedil;&atilde;o falha por erros do sistema. Pagamentos de assinatura s&atilde;o processados pelo AbacatePay.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">5. Uso Aceit&aacute;vel</h2>
        <p className="text-tx2 text-sm leading-relaxed mb-3">Voc&ecirc; concorda em n&atilde;o:</p>
        <ul className="list-disc pl-6 text-tx2 text-sm leading-relaxed space-y-2">
          <li>Enviar imagens que contenham conte&uacute;do ilegal, prejudicial ou ofensivo</li>
          <li>Usar o servi&ccedil;o para gerar conte&uacute;do enganoso ou enganador</li>
          <li>Tentar engenharia reversa ou abusar dos modelos de IA</li>
          <li>Exceder limites de uso ou contornar restri&ccedil;&otilde;es</li>
          <li>Revender ou redistribuir conte&uacute;do gerado sem os devidos direitos</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">6. Propriedade Intelectual</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          Voc&ecirc; mant&eacute;m a propriedade das imagens que envia. V&iacute;deos gerados pelo servi&ccedil;o podem ser usados para seus fins comerciais. A plataforma Genfy, marca e tecnologia subjacente permanecem como nossa propriedade intelectual.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">7. Limita&ccedil;&atilde;o de Responsabilidade</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          O Genfy &eacute; fornecido &quot;como est&aacute;&quot; sem garantias de qualquer tipo. N&atilde;o somos respons&aacute;veis por quaisquer danos indiretos, incidentais ou consequentes decorrentes do uso do servi&ccedil;o. Nossa responsabilidade total n&atilde;o exceder&aacute; o valor pago por voc&ecirc; nos &uacute;ltimos 12 meses.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">8. Altera&ccedil;&otilde;es nos Termos</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          Reservamo-nos o direito de modificar estes termos a qualquer momento. O uso cont&iacute;nuo do servi&ccedil;o ap&oacute;s altera&ccedil;&otilde;es constitui aceita&ccedil;&atilde;o dos termos modificados.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-tx mb-3">9. Contato</h2>
        <p className="text-tx2 text-sm leading-relaxed">
          Para d&uacute;vidas sobre estes Termos, entre em contato atrav&eacute;s de nossas redes sociais ou pela se&ccedil;&atilde;o de suporte do aplicativo.
        </p>
      </section>
    </>
  );
}

export default function TermsPage() {
  const { lang } = useLang();

  return (
    <div className="min-h-screen relative">
      <AnimatedOrbs />
      <Navbar />
      <main className="relative z-10 pt-28 pb-16">
        <div className="max-w-3xl mx-auto px-6">
          <article className="glass-card p-8 md:p-12">
            {lang === "pt" ? <TermsPT /> : <TermsEN />}
          </article>
        </div>
      </main>
      <Footer />
    </div>
  );
}
